### PR TITLE
Contract calls

### PR DESCRIPTION
**Pull request by dtebbs**

### CODE REVIEW

**Review by magnitis — APPROVED** [review]
LGTM

**Comment by aiman** [comment]
I am running `make check` and encountering:

```
$ make check
mypy -p autcli -p tests
autcli/utils.py:547: error: "Type[ABIManager]" has no attribute "load_abi_file"
autcli/commands/contract.py:48: error: Cannot find implementation or library stub for module named "autonity.abi_parser"
autcli/commands/contract.py:48: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 21 source files)
make: *** [Makefile:17: check-types] Error 1
```

**Comment by aiman** [comment]
Never mind, I switched branches and didn't update submodule :facepalm:

**Comment by aiman** [comment]
This is really cool.

**Comment by aiman** [comment]
One thing I wondered about is the type conversion for method parameters from the shell. I can see how the conversion works for almost all Solidity types. The only one I'm not sure about is when structs are passed as parameters. Are there any tests around this?

**Comment by dtebbs** [comment]
> One thing I wondered about is the type conversion for method parameters from the shell. I can see how the conversion works for almost all Solidity types. The only one I'm not sure about is when structs are passed as parameters. Are there any tests around this?

Good question.  Unfortunately, structs etc are not yet supported. 
 (https://github.com/autonity/autonity.py/blob/master/autonity/abi_parser.py#L99).

**Comment by dtebbs** [comment]
Issue in autonity.py regarding the complex input types  autonity/autonity.py#18

**Review by aiman — APPROVED** [review]
Thanks for clarifying, LGTM.

**Pull request merged**
